/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CartId = bigint;
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'buyerId' : Principal,
  'shippingAddress' : string,
  'items' : Array<ShoppingCartItem>,
}
export type OrderId = bigint;
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'sellerId' : Principal,
  'inventoryCount' : bigint,
  'image' : ExternalBlob,
  'priceInCents' : bigint,
}
export type ProductId = bigint;
export interface Review {
  'id' : ReviewId,
  'createdAt' : Time,
  'productId' : ProductId,
  'reviewerId' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ShoppingCart {
  'id' : CartId,
  'ownerId' : Principal,
  'createdAt' : Time,
  'isActive' : boolean,
  'items' : Array<ShoppingCartItem>,
}
export interface ShoppingCartItem {
  'priceSnapshotInCents' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addItemToCart' : ActorMethod<[CartId, ShoppingCartItem], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[CartId], undefined>,
  'createCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Principal, CartId, string], undefined>,
  'deleteCart' : ActorMethod<[CartId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteReview' : ActorMethod<[ReviewId], undefined>,
  'getActiveProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getAllAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[CartId], ShoppingCart>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrdersByBuyer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByProduct' : ActorMethod<[ProductId], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  /**
   * / ***********************************************
   * /    * UTILITY FUNCTIONS                              *
   * /    ************************************************
   */
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProductPrice' : ActorMethod<[ProductId], bigint>,
  'getProductsBySeller' : ActorMethod<[Principal], Array<Product>>,
  'getRecentOrders' : ActorMethod<[bigint], Array<Order>>,
  'getReviewsByProduct' : ActorMethod<[ProductId], Array<Review>>,
  'getReviewsByReviewer' : ActorMethod<[Principal], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / ***********************************************
   * /    * USER PROFILES                                  *
   * /    ************************************************
   */
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProductInStock' : ActorMethod<[ProductId], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'leaveReview' : ActorMethod<[ProductId, bigint, string], undefined>,
  'removeCategory' : ActorMethod<[string], undefined>,
  'removeItemFromCart' : ActorMethod<[CartId, ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / ***********************************************
   * /    * SEARCH & FILTERS                               *
   * /    ************************************************
   */
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];